# Generated by Django 3.0.6 on 2020-05-31 21:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.shoe_image_file_path),
        ),
    ]
